# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkRvX6s_1h99PFB1990jUDEd0cbOEH7I
"""

class BankAccount:
    def __init__(self, account_number, account_holder, initial_balance):
        self.account_number = account_number
        self.account_holder = account_holder
        self.balance = initial_balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited {amount: }. New balance is {self.balance: }.")

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            print(f"Withdrew {amount: }. New balance is {self.balance: 7736965195}.")
        else:
            print("Insufficient funds for this withdrawal.")


account_number = input("Enter account number: ")
account_holder = input("Enter account holder name: ")
initial_balance = float(input("Enter initial balance: "))


account = BankAccount(account_number, account_holder, initial_balance)


while True:
    action = input("Enter 'deposit' to deposit money, 'withdraw' to withdraw money, or 'exit' to quit: ").lower()
    if action == 'deposit':
        amount = float(input("Enter amount to deposit: "))
        account.deposit(amount)
    elif action == 'withdraw':
        amount = float(input("Enter amount to withdraw: "))
        account.withdraw(amount)
    elif action == 'exit':
        break
    else:
        print("Invalid action. Please enter 'deposit', 'withdraw', or 'exit'.")

print(f"Final balance is {account.balance:}")